// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdqobiQkw-qAzpNVEyKHhGPnSgJEv2Ls',
    appId: '1:944441822371:web:86430bb437ad55262e8316',
    messagingSenderId: '944441822371',
    projectId: 'crud-8f87b',
    authDomain: 'crud-8f87b.firebaseapp.com',
    storageBucket: 'crud-8f87b.firebasestorage.app',
    measurementId: 'G-6CQB99KMJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbM8I4tzPiSawkysDvHWOcHsrz_bumBYo',
    appId: '1:944441822371:android:56f2fe314f0b28fb2e8316',
    messagingSenderId: '944441822371',
    projectId: 'crud-8f87b',
    storageBucket: 'crud-8f87b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpeT3kBOdF6FxR5OzONMM8lf9kGXyIxA',
    appId: '1:944441822371:ios:31b3afb730a3a0e32e8316',
    messagingSenderId: '944441822371',
    projectId: 'crud-8f87b',
    storageBucket: 'crud-8f87b.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpeT3kBOdF6FxR5OzONMM8lf9kGXyIxA',
    appId: '1:944441822371:ios:31b3afb730a3a0e32e8316',
    messagingSenderId: '944441822371',
    projectId: 'crud-8f87b',
    storageBucket: 'crud-8f87b.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkdqobiQkw-qAzpNVEyKHhGPnSgJEv2Ls',
    appId: '1:944441822371:web:9abd27ab5e8994d12e8316',
    messagingSenderId: '944441822371',
    projectId: 'crud-8f87b',
    authDomain: 'crud-8f87b.firebaseapp.com',
    storageBucket: 'crud-8f87b.firebasestorage.app',
    measurementId: 'G-1J4NP5RH07',
  );
}
